---
homebrew_taps:
  - { name: caskroom/cask }
  - { name: homebrew/binary }
  - { name: homebrew/dupes }
  - { name: caskroom/fonts }
  - { name: caskroom/versions }
  - { name: sanemat/font }
  - { name: kevwil/patches }
  - { name: bfontaine/utils }
  - { name: yudai/gotty }

homebrew_packages:
  - { name: brew-cask }
  - { name: ghq, install_options: completions}
  - { name: pcre }
  - { name: libxml2 }
  - { name: glib }
  - { name: fontconfig }
  - { name: readline }
  - { name: openssl }
  - { name: python }
  - { name: coreutils }
  - { name: git }
  - { name: zsh, install_options: disable-etcdir }
  - { name: wget }
  - { name: curl }
  - { name: cmake }
  - { name: autoconf }
  - { name: automake }
  - { name: pkg-config }
  - { name: ctags }
  - { name: tree }
  - { name: nkf }
  - { name: jq }
  - { name: go }
  - { name: direnv }
  - { name: peco }
  - { name: hub }
  - { name: rbenv }
  - { name: ruby-build }
  - { name: rbenv-binstubs }
  - { name: rbenv-gem-rehash }
  - { name: w3m }
  - { name: tmux }
  - { name: reattach-to-user-namespace }
  - { name: sha2 }
  - { name: xz }
  - { name: lua }
  - { name: vim, install_options: with-lua }
  - { name: rsense }
  - { name: pyenv }
  - { name: plenv }
  - { name: perl-build }
  - { name: awscli }
  - { name: gpg }
  - { name: msmtp }
  - { name: getmail }
  - { name: abook }
  - { name: ripmime }
  - { name: extract_url }
  - { name: weechat, install_options: "with-ruby, with-python, with-perl" }
  - { name: rfc }
  - { name: mobile-shell }
  - { name: xhyve }
  - { name: gotty }
  - { name: ricty }
  - { name: mutt, install_options: "with-sidebar-patch, with-confirm-attachement-patch, with-trash-patch" }
  - { name: muttils }
  - { name: npm }

homebrew_cask_packages:
  - { name: avast }
  - { name: iterm2 }
  - { name: firefox }
  - { name: google-japanese-ime }
  - { name: java }
  - { name: skype }
  - { name: slack }
  - { name: karabiner }
  - { name: vagrant }
  - { name: virtualbox }
  - { name: vlc }
  - { name: kindle }
  - { name: xquartz }
  - { name: alfred }
  - { name: shiftit }
  - { name: gimp }
  - { name: terraform }
  - { name: packer }
  - { name: macvim }

npm_packages:
  - { name: http-console }
