---
- name: Restart Dock
  shell: |
    killall Dock

- name: Restart Finder
  shell: |
    killall Finder

- name: Setup Karabiner
  shell: |
    ./karabiner.sh
  args:
    chdir: roles/mac/files/bin

- name: Restore iterm2 configuration
  shell: |
    plutil -convert binary1 -o "{{ ansible_user_dir }}/Library/Preferences/com.googlecode.iterm2.plist" ./com.googlecode.iterm2.plist
  args:
    chdir: roles/mac/files/Library/Preferences

- name: Change login shell
  become: true
  shell: |
    dscl . -create /Users/$USER UserShell /usr/local/bin/zsh

- name: Setup launchd for compressing tmux logs
  become: true
  shell: |
    launchctl load "{{ ansible_user_dir }}/Library/LaunchAgents/local.compresstmuxlog.plist"

- name: Run fc-cache
  shell: |
    fc-cache -vf
