---
- name: Install gem pacakges
  gem:
    name: "{{ item.name }}"
    state: "{{ item.state | default('present') }}"
    executable: /Users/knakayama/.rbenv/shims/gem
  with_items: gem_packages
  tags:
      - gem
