---
- name: Check if login shell is /usr/local/bin/zsh
  shell: |
    echo $SHELL
  register: res
  failed_when: false
  always_run: true
  changed_when: res.stdout.find('/usr/local/bin/zsh') == -1
  notify:
    - Change login shell

- name: Check if iterm2 config is differ
  shell: |
    diff <(plutil -convert binary1 -o - ./com.googlecode.iterm2.plist | md5 -q) <(md5 -q "{{ ansible_user_dir }}/Library/Preferences/com.googlecode.iterm2.plist")
  args:
    chdir: roles/mac/files/Library/Preferences
    executable: /bin/bash
  register: diff_result
  always_run: true
  failed_when: false
  changed_when: diff_result.rc != 0
  notify:
    - Restore iterm2 configuration

- name: Copy Karabiner private.xml
  file:
    src: "{{ ansible_user_dir }}/.ghq/github.com/knakayama/mac-os-x-setup/roles/mac/files/Library/Application\ Support/Karabiner/private.xml"
    dest: "{{ ansible_user_dir }}/Library/Application\ Support/Karabiner/private.xml"
    state: link
  notify:
    - Setup Karabiner

- name: Create alias symlink
  file:
    src: "{{ item.src }}"
    dest: "/usr/local/bin/{{ item.dest }}"
    state: link
  with_items:
    - "{{ symlinks }}"

- name: Copy local.knakayama.compresstmuxlog.plist
  become: yes
  template:
    src: Library/LaunchAgents/local.knakayama.compresstmuxlog.plist.j2
    dest: "{{ ansible_user_dir }}/Library/LaunchAgents/local.compresstmuxlog.plist"
    owner: root
    group: staff
    mode: 0644
  notify:
    - Setup launchd for compressing tmux logs

- name: Check if compressing tmux log launchd exists
  shell: |
    launchctl list
  register: launchctl_result
  always_run: true
  failed_when: false
  changed_when: launchctl_result.stdout.find('compresstmuxlog') == -1
  notify:
    - Setup launchd for compressing tmux logs
