---
- name: Change login shell to /usr/local/bin/zsh
  user:
    name: "{{ ansible_user_id }}"
    shell: /usr/local/bin/zsh

- name: Check if iterm2 config is differ
  shell: |
    diff <(plutil -convert binary1 -o - ./com.googlecode.iterm2.plist | md5 -q) <(md5 -q "{{ ansible_user_dir }}/Library/Preferences/com.googlecode.iterm2.plist")
  args:
    chdir: roles/mac/files/Library/Preferences
    executable: /bin/bash
  register: diff_result
  always_run: true
  failed_when: false
  changed_when: diff_result.rc != 0
  notify:
    - Restore iterm2 configuration

- name: Copy Karabiner private.xml
  file:
    src: "{{ ansible_user_dir }}/.ghq/github.com/knakayama/mac-os-x-setup/roles/mac/files/Library/Application\ Support/Karabiner/private.xml"
    dest: "{{ ansible_user_dir }}/Library/Application\ Support/Karabiner/private.xml"
    state: link
  notify:
    - Setup Karabiner

- name: Create alias symlink
  file:
    src: "{{ item.src }}"
    dest: "/usr/local/bin/{{ item.dest }}"
    state: link
  with_items:
    - "{{ symlinks }}"

- name: Install ricty fonts
  shell: |
    cp -f $(brew --cellar ricty)/*/share/fonts/Ricty*.ttf "{{ ansible_user_id }}/Library/Fonts" && fc-cache -vf
  args:
    creates: "{{ ansible_user_id }}/Library/Fonts/Ricty-Bold.ttf"
