---
- name: Clone git repositories
  git:
    repo: "{{ item.repo }}"
    dest: "{{ item.dest }}"
  with_items: git_repositories

- name: Setup my git repositories
  shell: |
    rake -t
  args:
    chdir: "{{ item.chdir }}"
    creates: "{{ item.creates }}"
  with_items:
    - { chdir: ~/.ghq/github.com/knakayama/credentials, creates: ~/.msmtprc }
    - { chdir: ~/.ghq/github.com/knakayama/dotfiles, creates: ~/.vimrc }
