---
- name: Check if homebrew already installed
  command: |
    type brew
  register: res
  failed_when: no
  always_run: yes
  changed_when: res.rc != 0

- name: Change /usr/local owners
  command: |
    chown $USER:staff /usr/local/share
    chown $USER:staff /usr/local/lib
  sudo: yes
  when: res|changed

- name: Install homebrew
  command: |
    ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
  when: res|changed

- name: Add homebrew taps
  homebrew_tap:
    tap: "{{ item.name }}"
    state: present
  with_items: homebrew_taps

- name: Update homebrew
  homebrew:
    update_homebrew: yes

- name: Install homebrew packages
  homebrew:
    name: "{{ item.name }}"
    state: "{{ item.state | default('latest') }}"
    install_options: "{{
      item.install_options | default() | join(',')
      if item.install_options is not string
      else item.install_options
    }}"
  with_items: homebrew_packages

- name: Install homebrew cask packages
  homebrew_cask:
    name: "{{ item.name }}"
    state: "{{ item.state | default('installed') }}"
  with_items: homebrew_cask_packages
