---
- name: Check if /usr/local owners
  stat:
    path: /usr/local
  register: res
  always_run: true
  failed_when: false
  changed_when: res.stat.pw_name != '{{ ansible_user_id }}'

- name: Change /usr/local owners
  become: true
  shell: |
    chown -R {{ ansible_user_id }}:admin /usr/local
  when: res|changed

- name: Install homebrew
  shell: |
    ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
  args:
    creates: /usr/local/bin/brew

- name: Add homebrew taps
  homebrew_tap:
    tap: "{{ item.tap }}"
    state: present
  with_items:
    - "{{ homebrew_taps }}"

- name: Update homebrew
  homebrew:
    update_homebrew: yes

- name: Install homebrew packages
  homebrew:
    name: "{{ item.name }}"
    state: "{{ item.state | default('latest') }}"
    install_options: "{{ item.install_options | default(omit) }}"
  with_items:
    - "{{ homebrew_packages }}"
    - "{{ homebrew_cask_packages }}"
