---
- name: Install gem pacakges
  gem:
    name: "{{ item.name }}"
    state: "{{ item.state | default('present') }}"
    executable: "{{ ansible_user_dir }}/.rbenv/shims/gem"
  with_items:
    - "{{ gem_packages }}"
