---
- name: Install rfc
  shell: |
    curl -sL https://raw.github.com/bfontaine/rfc/master/rfc > /usr/local/bin/rfc  && chmod +x /usr/local/bin/rfc
  args:
    creates: /usr/local/bin/rfc

- name: Clone termtile
  shell: |
    ghq get git@github.com:apaszke/termtile.git
  args:
    creates: ~/.ghq/github.com/apaszke/termtile/README.md

- name: Install termtile
  shell: |
    ./install.sh yes
  args:
    chdir: ~/.ghq/github.com/apaszke/termtile
    creates: ~/.termtile/getScreenInfo
