---
- name: Clone tools
  git:
    repo: "{{ item.repo }}"
    dest: "{{ item.dest }}"
  with_items:
    - "{{ tools }}"

- name: Install termtile
  shell: |
    ./install.sh yes
  args:
    chdir: ~/.ghq/github.com/apaszke/termtile
    creates: ~/.termtile/getScreenInfo

- name: Install pwd.sh
  file:
    src: ~/.ghq/github.com/drduh/pwd.sh/pwd.sh
    dest: /usr/local/bin/pwd.sh
    state: link

- name: Install translate-shell
  shell: |
    brew install http://www.soimort.org/translate-shell/translate-shell.rb
  args:
    creates: /usr/local/bin/trans
