---
- name: Clone tools
  git:
    repo: "{{ item.repo }}"
    dest: "{{ item.dest }}"
  with_items:
    - "{{ tools }}"

- name: Install termtile
  shell: |
    ./install.sh yes
  args:
    chdir: "{{ ansible_user_dir }}/.ghq/github.com/apaszke/termtile"
    creates: "{{ ansible_user_dir }}/.termtile/getScreenInfo"

- name: Install pwd.sh
  file:
    src: "{{ ansible_user_dir }}/.ghq/github.com/drduh/pwd.sh/pwd.sh"
    dest: /usr/local/bin/pwd.sh
    state: link

- name: Install git-secrets
  shell: |
    make install
  args:
    chdir: "{{ ansible_user_dir }}/.ghq/github.com/awslabs/git-secrets"
    creates: /usr/local/bin/git-secrets

- name: Install hashicorp cli completions
  get_url:
    url: "{{ item.url }}"
    dest: "{{ ansible_user_dir }}/.zsh/completions/{{ item.dest }}"
  with_items:
    - "{{ hashicorp_tools }}"
