---
- name: Clone tools
  git:
    repo: git@github.com:apaszke/termtile.git
    dest: ~/.ghq/github.com/apaszke/termtile

- name: Install termtile
  shell: |
    ./install.sh yes
  args:
    chdir: ~/.ghq/github.com/apaszke/termtile
    creates: ~/.termtile/getScreenInfo

- name: Install translate-shell
  shell: |
    brew install http://www.soimort.org/translate-shell/translate-shell.rb
  args:
    creates: /usr/local/bin/trans
