---
- name: Install rfc
  shell: |
    curl -sL https://raw.github.com/bfontaine/rfc/master/rfc > /usr/local/bin/rfc  && chmod +x /usr/local/bin/rfc
  args:
    creates: /usr/local/bin/rfc

- name: Clone termtile
  git:
    repo: git@github.com:apaszke/termtile.git
    dest: ~/.ghq/github.com/apaszke/termtile

- name: Install termtile
  shell: |
    ./install.sh yes
  args:
    chdir: ~/.ghq/github.com/apaszke/termtile
    creates: ~/.termtile/getScreenInfo

- name: Install translate-shell
  shell: |
    brew install http://www.soimort.org/translate-shell/translate-shell.rb
  args:
    creates: /usr/local/bin/trans
