---
- name: Clone tools
  git:
    repo: "{{ item.repo }}"
    dest: "{{ item.dest }}"
  with_items:
    - "{{ tools }}"

- name: Install termtile
  shell: |
    ./install.sh yes
  args:
    chdir: ~/.ghq/github.com/apaszke/termtile
    creates: ~/.termtile/getScreenInfo

- name: Install pwd.sh
  file:
    src: ~/.ghq/github.com/drduh/pwd.sh/pwd.sh
    dest: /usr/local/bin/pwd.sh
    state: link

- name: Install translate-shell
  shell: |
    brew install http://www.soimort.org/translate-shell/translate-shell.rb
  args:
    creates: /usr/local/bin/trans

- name: Install git-secrets
  shell: |
    make install
  args:
    chdir: ~/.ghq/github.com/awslabs/git-secrets
    creates: /usr/local/bin/git-secrets

- name: Install hashicorp cli completions
  get_url:
    url: "{{ item.url }}"
    dest: "~/.zsh/completions/{{ item.dest }}"
    mode: 0644
  with_items:
    - "{{ hashicorp_tools }}"
