---
- name: Install Ruby via rbenv
  shell: |
    bash -cl 'rbenv install "{{ ruby_version }}"'
  args:
    creates: "~/.rbenv/versions/{{ ruby_version }}/bin/ruby"

- name: Install gem pacakges
  gem:
    name: "{{ item.name }}"
    include_doc: yes
    executable: "{{ ansible_user_dir }}/.rbenv/shims/gem"
    state: "{{ item.state | default('latest') }}"
  with_items:
    - "{{ gem_packages }}"
