---
go_packages:
  - { name: httpdoc, path: github.com/bfontaine/httpdoc }
  - { name: gommit-m, path: github.com/yuroyoro/gommit-m }
  - { name: gore, path: github.com/motemen/gore }
  - { name: getool, path: github.com/garyburd/go-explorer/src/getool }
  - { name: gotty, path: github.com/yudai/gotty }
  - { name: ghs, path: github.com/sona-tar/ghs }
  - { name: ghdump, path: github.com/knakayama/ghdump }
